services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: buku_db
      POSTGRES_USER: buku_user
      POSTGRES_PASSWORD: buku_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U buku_user -d buku_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data: