# Generated by Django 6.1.1 on 2026-09-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='issued_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='buku',
            name='writer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
