# Generated by Django 6.1.1 on 2026-09-18 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0002_buku_issued_date_buku_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='completed',
        ),
    ]
